'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace spbadm4_EWS
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CreateCalendarEventType", [Namespace]:="http://schemas.datacontract.org/2004/07/EskEWSService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CreateCalendarEventType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BodyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CalendarEventIDOldField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FinishField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LoginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubjectField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimezoneField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Body() As String
            Get
                Return Me.BodyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BodyField, value) <> true) Then
                    Me.BodyField = value
                    Me.RaisePropertyChanged("Body")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CalendarEventIDOld() As String
            Get
                Return Me.CalendarEventIDOldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CalendarEventIDOldField, value) <> true) Then
                    Me.CalendarEventIDOldField = value
                    Me.RaisePropertyChanged("CalendarEventIDOld")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Finish() As Date
            Get
                Return Me.FinishField
            End Get
            Set
                If (Me.FinishField.Equals(value) <> true) Then
                    Me.FinishField = value
                    Me.RaisePropertyChanged("Finish")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Login() As String
            Get
                Return Me.LoginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LoginField, value) <> true) Then
                    Me.LoginField = value
                    Me.RaisePropertyChanged("Login")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Start() As Date
            Get
                Return Me.StartField
            End Get
            Set
                If (Me.StartField.Equals(value) <> true) Then
                    Me.StartField = value
                    Me.RaisePropertyChanged("Start")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Subject() As String
            Get
                Return Me.SubjectField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubjectField, value) <> true) Then
                    Me.SubjectField = value
                    Me.RaisePropertyChanged("Subject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Timezone() As String
            Get
                Return Me.TimezoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimezoneField, value) <> true) Then
                    Me.TimezoneField = value
                    Me.RaisePropertyChanged("Timezone")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DeleteCalendarEventType", [Namespace]:="http://schemas.datacontract.org/2004/07/EskEWSService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DeleteCalendarEventType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CalendarEventIDOldField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LoginField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CalendarEventIDOld() As String
            Get
                Return Me.CalendarEventIDOldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CalendarEventIDOldField, value) <> true) Then
                    Me.CalendarEventIDOldField = value
                    Me.RaisePropertyChanged("CalendarEventIDOld")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Login() As String
            Get
                Return Me.LoginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LoginField, value) <> true) Then
                    Me.LoginField = value
                    Me.RaisePropertyChanged("Login")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="spbadm4_EWS.IEskEWSService")>  _
    Public Interface IEskEWSService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEskEWSService/CreateCalendarEvent", ReplyAction:="http://tempuri.org/IEskEWSService/CreateCalendarEventResponse")>  _
        Function CreateCalendarEvent(ByVal MyEvent As spbadm4_EWS.CreateCalendarEventType) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEskEWSService/DeleteCalendarEvent", ReplyAction:="http://tempuri.org/IEskEWSService/DeleteCalendarEventResponse")>  _
        Function DeleteCalendarEvent(ByVal MyEvent As spbadm4_EWS.DeleteCalendarEventType) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IEskEWSServiceChannel
        Inherits spbadm4_EWS.IEskEWSService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EskEWSServiceClient
        Inherits System.ServiceModel.ClientBase(Of spbadm4_EWS.IEskEWSService)
        Implements spbadm4_EWS.IEskEWSService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CreateCalendarEvent(ByVal MyEvent As spbadm4_EWS.CreateCalendarEventType) As String Implements spbadm4_EWS.IEskEWSService.CreateCalendarEvent
            Return MyBase.Channel.CreateCalendarEvent(MyEvent)
        End Function
        
        Public Function DeleteCalendarEvent(ByVal MyEvent As spbadm4_EWS.DeleteCalendarEventType) As String Implements spbadm4_EWS.IEskEWSService.DeleteCalendarEvent
            Return MyBase.Channel.DeleteCalendarEvent(MyEvent)
        End Function
    End Class
End Namespace
